#pragma once

#define MASTER_LEFT
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 425
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 100
#define TAPPING_TOGGLE 2
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD